### ISSUE TITLE
Explore Backend implementations

### ISSUE THREAD

**Issue by adampwll** [adampwll/feast-hall#2]
Investigate implementing a backend. Will need to interface with some data store to persist and load data (users, profiles, lists, etc.)
Two possibilities (not inclusive):
- NodeJs/Express
- Java

**Comment by adampwll** [comment]
Likely Express/Node backend.

**Comment by dillbow** [comment]
Beginning basic setup of express and node, will likely throw up PR for a basic endpoint later today.

**Comment by dillbow** [comment]
Going to start exploring setting up a node/express backend. Will likely start with a "helloworld" or template endpoint in a PR.

**Comment by adampwll** [comment]
Is there any remaining work on this issue, or should I close it out and create some more tix?

**Comment by dillbow** [comment]
I've set up the bare basics for a backend (basic get endpoint and a call to it from frontend). We don't yet have data persistence and i'm working on wiring mongo up currently.

**Comment by adampwll** [comment]
Backend frame created, PR 14 currently in review to connect mongoDB
